import { StyleSheet } from "react-native";
import { Spacing } from "./spacing";

export const Typography = StyleSheet.create({
  jumbo: {
    fontFamily: "Arial",
    fontSize: 30,
    color: "#1D2733",
    marginTop: Spacing.none,
    marginBottom: Spacing.sm,
    marginLeft: Spacing.none,
    marginRight: Spacing.none,
  },
  heading1: {
    fontFamily: "Arial",
    fontSize: 22,
    color: "#1D2733",
    marginTop: Spacing.none,
    marginBottom: Spacing.md,
    marginLeft: Spacing.none,
    marginRight: Spacing.none,
  },
  heading2: {
    fontFamily: "Arial",
    fontSize: 16,
    color: "#1D2733",
    marginTop: Spacing.none,
    marginBottom: Spacing.md,
    marginLeft: Spacing.none,
    marginRight: Spacing.none,
  },
  body: {
    fontFamily: "Arial",
    fontSize: 16,
    lineHeight: 20,
    color: "#999",
    marginTop: Spacing.none,
    marginBottom: Spacing.none,
    marginLeft: Spacing.none,
    marginRight: Spacing.none,
  },
  bodySmall: {
    fontFamily: "Arial",
    fontSize: 14,
    lineHeight: 16,
    color: "#999",
    marginTop: Spacing.none,
    marginBottom: Spacing.none,
    marginLeft: Spacing.none,
    marginRight: Spacing.none,
  },
  formLabel: {
    fontFamily: "Arial",
    fontSize: 16,
    lineHeight: 20,
    color: "#333",
    marginTop: Spacing.none,
    marginBottom: Spacing.none,
    marginLeft: Spacing.none,
    marginRight: Spacing.none,
  },
  toastHeading: {
    fontFamily: "Arial",
    fontSize: 16,
    lineHeight: 20,
    marginTop: Spacing.sm,
    marginBottom: Spacing.xs,
    marginLeft: Spacing.none,
    marginRight: Spacing.none,
  },
  toastBody: {
    fontFamily: "Arial",
    fontSize: 16,
    lineHeight: 20,
    color: "#999",
    marginTop: Spacing.none,
    marginBottom: Spacing.none,
    marginLeft: Spacing.none,
    marginRight: Spacing.none,
  },
});
